# Generated by Django 4.0.5 on 2022-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_rename_body_question_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
